In [2]:
import numpy as np

print('------------------------------------------')
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a1)
print('------------------------------------------')

m1 = np.zeros((3, 3))
print(m1)

print('------------------------------------------')
m2 = np.random.randint(1, 11, size=(5, 5))
print(m2)
print('------------------------------------------')
m3 = np.random.randint(0, 2, size=(4, 4))
print(m3)
print('------------------------------------------')
a21 = np.random.randint(1, 11, size=(1, 5))
a22 = np.random.randint(1, 11, size=(1, 5))
print(a21)
print(a22)
asum = a22 + a21
print(asum)
adel = a22 - a21
print(adel)
am = a22 * a21
print(am)
print('------------------------------------------')
a31 = np.random.randint(1, 11, size=(1, 7))
a32 = np.random.randint(1, 11, size=(1, 7))
print(a31)
print(a32)
print(a31 * a32)
print('------------------------------------------')
m41 = np.random.randint(1, 11, size=(2, 2))
m42 = np.random.randint(1, 11, size=(2, 3))
c = np.dot(m41, m42)
print(c)
print('------------------------------------------')
m5 = np.random.randint(1, 11, size=(3, 3))
print(m5)
m5_inv = np.linalg.inv(m5)
print(m5_inv)
print('------------------------------------------')
m6 = np.random.randint(0, 2, size=(4, 4))
print(m6)
b = m6.T
print(b)
print('------------------------------------------')
m7 = np.random.randint(1, 11, size=(3, 4))
a4 = np.random.randint(1, 11, size=(1, 4))
print(m7)
print(a4)
print(m7 * a4)
print('------------------------------------------')
m8 = np.random.randint(0, 2, size=(2, 3))
a5 = np.random.randint(0, 2, size=(1, 3))
print(m8)
print(a5)
print(m8 * a5)
print('------------------------------------------')
m91 = np.random.randint(1, 11, size=(2, 2))
m92 = np.random.randint(1, 11, size=(2, 2))
print(m91)
print(m92)

print(m91 * m92)
print('------------------------------------------')
m91 = np.random.randint(1, 11, size=(2, 2))
m92 = np.random.randint(1, 11, size=(2, 2))
print(m91)
print(m92)
c = np.dot(m91, m92)
print(c)
print('------------------------------------------')
m10 = np.random.randint(1, 101, size=(5, 5))
print(m10)
print(np.sum(m10))
print('------------------------------------------')
m111 = np.random.randint(1, 11, size=(4, 4))
m112 = np.random.randint(1, 11, size=(4, 4))
print(m111)
print(m112)
print(m111 - m112)
print('------------------------------------------')
m12 = np.random.randint(0, 2, size=(3, 3))
print(m12)
print(np.sum(m12, axis=1, keepdims=True))

print('------------------------------------------')
m12 = np.random.randint(1, 12, size=(3, 4))
print(m12)
m13 = m12 ** 2
print(13)
print('------------------------------------------')
a6 = np.random.randint(1, 51, size=(1, 4))
print(a6)
a7 = a6 // 2
print(a7)


------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------
[[ 4 10  4  3  6]
 [ 9  1  6  7 10]
 [ 6  7  5  4  9]
 [ 4  9  8  1  5]
 [ 9 10  8  3  4]]
------------------------------------------
[[1 1 1 0]
 [0 0 1 1]
 [0 0 0 1]
 [1 0 0 1]]
------------------------------------------
[[10  2  6  8  4]]
[[7 4 4 7 4]]
[[17  6 10 15  8]]
[[-3  2 -2 -1  0]]
[[70  8 24 56 16]]
------------------------------------------
[[5 5 2 1 4 8 4]]
[[ 9  4  6  3  1 10  3]]
[[45 20 12  3  4 80 12]]
------------------------------------------
[[ 33  73  77]
 [ 67 100 142]]
------------------------------------------
[[ 6 10  9]
 [ 5  3  2]
 [ 6  3  4]]
[[-0.08450704  0.18309859  0.09859155]
 [ 0.11267606  0.42253521 -0.46478873]
 [ 0.04225352 -0.5915493   0.45070423]]
------------------------------------------
[[0 1 1 1]
 [0 1 0 0]
 [1 0 1 1]
 [0 0 0 1]]
[[0 0 1 0]
 [1 1 0 